FROM node:25.5-slim

WORKDIR /usr/src/7-gui-react

RUN npm install -g pnpm@latest-10

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

RUN pnpm exec playwright install

RUN pnpm exec playwright install-deps

CMD [ "pnpm", "test" ]